### ISSUE TITLE
Add information about this plugin to main documentation

### ISSUE THREAD

**Issue by ezhlobo** [kaminaly/vscode-react-pug#1]
Hey. I'was looking for anything to turn on syntax highlighting in VSCode for pug in javascript and found this. Thank you very much!

I realized similar extension which was delivered near the same time: https://github.com/zokugun/vscode-pug-template-literal

I suggest you, @kaminaly, or @zokugun create a PR to main documentation, so other people will know that something like this exists.

It's not a big deal, you can check how we added information for WebStorm: https://github.com/pugjs/babel-plugin-transform-react-pug/pull/60

**Comment by kaminaly** [comment]
Wow, interesting! I didn't know that similar extension...
Ok, thanks, I will create a PR soon! This extension still has some small problems though.

**Comment by ezhlobo** [comment]
@kaminaly ah, will be nice if you can mention all problems within issues or in README, so others will be aware of them ;).

**Comment by kaminaly** [comment]
@ezhlobo yeah, that's right. I should do that before sending a PR and I will do that :)

**Comment by ezhlobo** [comment]
@kaminaly hey, do you need a hand with that? :)

**Comment by kaminaly** [comment]
@ezhlobo hi, thanks for your concern. I was really busy. But, finally, I've sent a PR :)
